window.codepoints = [
    { start: 0x0020, end: 0x007F, name: "Basic Latin", enabled: true, },
    { start: 0x00A0, end: 0x00FF, name: "Latin-1 Supplement", enabled: true, },
    { start: 0x0100, end: 0x017F, name: "Latin Extended-A", enabled: true, },
    { start: 0x0180, end: 0x024F, name: "Latin Extended-B", enabled: true, },
    { start: 0x0250, end: 0x02AF, name: "IPA Extensions", enabled: true, },
    { start: 0x02B0, end: 0x02FF, name: "Spacing Modifier Letters", enabled: true, },
    { start: 0x0300, end: 0x036F, name: "Combining Diacritical Marks", enabled: true, },
    { start: 0x0370, end: 0x03FF, name: "Greek and Coptic", enabled: true, },
    { start: 0x0400, end: 0x04FF, name: "Cyrillic", enabled: true, },
    { start: 0x0500, end: 0x052F, name: "Cyrillic Supplementary", enabled: true, },
    { start: 0x0530, end: 0x058F, name: "Armenian", enabled: true, },
    { start: 0x0590, end: 0x05FF, name: "Hebrew", enabled: true, },
    { start: 0x0600, end: 0x06FF, name: "Arabic", enabled: true, },
    { start: 0x0700, end: 0x074F, name: "Syriac", enabled: true, },
    { start: 0x0780, end: 0x07BF, name: "Thaana", enabled: true, },
    { start: 0x0900, end: 0x097F, name: "Devanagari", enabled: true, },
    { start: 0x0980, end: 0x09FF, name: "Bengali", enabled: true, },
    { start: 0x0A00, end: 0x0A7F, name: "Gurmukhi", enabled: true, },
    { start: 0x0A80, end: 0x0AFF, name: "Gujarati", enabled: true, },
    { start: 0x0B00, end: 0x0B7F, name: "Oriya", enabled: true, },
    { start: 0x0B80, end: 0x0BFF, name: "Tamil", enabled: true, },
    { start: 0x0C00, end: 0x0C7F, name: "Telugu", enabled: true, },
    { start: 0x0C80, end: 0x0CFF, name: "Kannada", enabled: true, },
    { start: 0x0D00, end: 0x0D7F, name: "Malayalam", enabled: true, },
    { start: 0x0D80, end: 0x0DFF, name: "Sinhala", enabled: true, },
    { start: 0x0E00, end: 0x0E7F, name: "Thai", enabled: true, },
    { start: 0x0E80, end: 0x0EFF, name: "Lao", enabled: true, },
    { start: 0x0F00, end: 0x0FFF, name: "Tibetan", enabled: true, },
    { start: 0x1000, end: 0x109F, name: "Myanmar", enabled: true, },
    { start: 0x10A0, end: 0x10FF, name: "Georgian", enabled: true, },
    { start: 0x1100, end: 0x11FF, name: "Hangul Jamo", enabled: true, },
    { start: 0x1200, end: 0x137F, name: "Ethiopic", enabled: true, },
    { start: 0x13A0, end: 0x13FF, name: "Cherokee", enabled: true, },
    { start: 0x1400, end: 0x167F, name: "Unified Canadian Aboriginal Syllabics", enabled: true, },
    { start: 0x1680, end: 0x169F, name: "Ogham", enabled: true, },
    { start: 0x16A0, end: 0x16FF, name: "Runic", enabled: true, },
    { start: 0x1700, end: 0x171F, name: "Tagalog", enabled: true, },
    { start: 0x1720, end: 0x173F, name: "Hanunoo", enabled: true, },
    { start: 0x1740, end: 0x175F, name: "Buhid", enabled: true, },
    { start: 0x1760, end: 0x177F, name: "Tagbanwa", enabled: true, },
    { start: 0x1780, end: 0x17FF, name: "Khmer", enabled: true, },
    { start: 0x1800, end: 0x18AF, name: "Mongolian", enabled: true, },
    { start: 0x1900, end: 0x194F, name: "Limbu", enabled: true, },
    { start: 0x1950, end: 0x197F, name: "Tai Le", enabled: true, },
    { start: 0x19E0, end: 0x19FF, name: "Khmer Symbols", enabled: true, },
    { start: 0x1D00, end: 0x1D7F, name: "Phonetic Extensions", enabled: true, },
    { start: 0x1E00, end: 0x1EFF, name: "Latin Extended Additional", enabled: true, },
    { start: 0x1F00, end: 0x1FFF, name: "Greek Extended", enabled: true, },
    { start: 0x2000, end: 0x206F, name: "General Punctuation", enabled: true, },
    { start: 0x2070, end: 0x209F, name: "Superscripts and Subscripts", enabled: true, },
    { start: 0x20A0, end: 0x20CF, name: "Currency Symbols", enabled: true, },
    { start: 0x20D0, end: 0x20FF, name: "Combining Diacritical Marks for Symbols", enabled: true, },
    { start: 0x2100, end: 0x214F, name: "Letterlike Symbols", enabled: true, },
    { start: 0x2150, end: 0x218F, name: "Number Forms", enabled: true, },
    { start: 0x2190, end: 0x21FF, name: "Arrows", enabled: true, },
    { start: 0x2200, end: 0x22FF, name: "Mathematical Operators", enabled: true, },
    { start: 0x2300, end: 0x23FF, name: "Miscellaneous Technical", enabled: true, },
    { start: 0x2400, end: 0x243F, name: "Control Pictures", enabled: true, },
    { start: 0x2440, end: 0x245F, name: "Optical Character Recognition", enabled: true, },
    { start: 0x2460, end: 0x24FF, name: "Enclosed Alphanumerics", enabled: true, },
    { start: 0x2500, end: 0x257F, name: "Box Drawing", enabled: true, },
    { start: 0x2580, end: 0x259F, name: "Block Elements", enabled: true, },
    { start: 0x25A0, end: 0x25FF, name: "Geometric Shapes", enabled: true, },
    { start: 0x2600, end: 0x26FF, name: "Miscellaneous Symbols", enabled: true, },
    { start: 0x2700, end: 0x27BF, name: "Dingbats", enabled: true, },
    { start: 0x27C0, end: 0x27EF, name: "Miscellaneous Mathematical Symbols-A", enabled: true, },
    { start: 0x27F0, end: 0x27FF, name: "Supplemental Arrows-A", enabled: true, },
    { start: 0x2800, end: 0x28FF, name: "Braille Patterns", enabled: true, },
    { start: 0x2900, end: 0x297F, name: "Supplemental Arrows-B", enabled: true, },
    { start: 0x2980, end: 0x29FF, name: "Miscellaneous Mathematical Symbols-B", enabled: true, },
    { start: 0x2A00, end: 0x2AFF, name: "Supplemental Mathematical Operators", enabled: true, },
    { start: 0x2B00, end: 0x2BFF, name: "Miscellaneous Symbols and Arrows", enabled: true, },
    { start: 0x2E80, end: 0x2EFF, name: "CJK Radicals Supplement", enabled: true, },
    { start: 0x2F00, end: 0x2FDF, name: "Kangxi Radicals", enabled: true, },
    { start: 0x2FF0, end: 0x2FFF, name: "Ideographic Description Characters", enabled: true, },
    { start: 0x3000, end: 0x303F, name: "CJK Symbols and Punctuation", enabled: true, },
    { start: 0x3040, end: 0x309F, name: "Hiragana", enabled: true, },
    { start: 0x30A0, end: 0x30FF, name: "Katakana", enabled: true, },
    { start: 0x3100, end: 0x312F, name: "Bopomofo", enabled: true, },
    { start: 0x3130, end: 0x318F, name: "Hangul Compatibility Jamo", enabled: true, },
    { start: 0x3190, end: 0x319F, name: "Kanbun", enabled: true, },
    { start: 0x31A0, end: 0x31BF, name: "Bopomofo Extended", enabled: true, },
    { start: 0x31F0, end: 0x31FF, name: "Katakana Phonetic Extensions", enabled: true, },
    { start: 0x3200, end: 0x32FF, name: "Enclosed CJK Letters and Months", enabled: true, },
    { start: 0x3300, end: 0x33FF, name: "CJK Compatibility", enabled: true, },
    { start: 0x3400, end: 0x4DBF, name: "CJK Unified Ideographs Extension A", enabled: true, },
    { start: 0x4DC0, end: 0x4DFF, name: "Yijing Hexagram Symbols", enabled: true, },
    { start: 0x4E00, end: 0x9FFF, name: "CJK Unified Ideographs", enabled: true, },
    { start: 0xA000, end: 0xA48F, name: "Yi Syllables", enabled: true, },
    { start: 0xA490, end: 0xA4CF, name: "Yi Radicals", enabled: true, },
    { start: 0xAC00, end: 0xD7AF, name: "Hangul Syllables", enabled: true, },
    { start: 0xD800, end: 0xDB7F, name: "High Surrogates", enabled: true, },
    { start: 0xDB80, end: 0xDBFF, name: "High Private Use Surrogates", enabled: true, },
    { start: 0xDC00, end: 0xDFFF, name: "Low Surrogates", enabled: true, },
    { start: 0xE000, end: 0xF8FF, name: "Private Use Area", enabled: true, },
    { start: 0xF900, end: 0xFAFF, name: "CJK Compatibility Ideographs", enabled: true, },
    { start: 0xFB00, end: 0xFB4F, name: "Alphabetic Presentation Forms", enabled: true, },
    { start: 0xFB50, end: 0xFDFF, name: "Arabic Presentation Forms-A", enabled: true, },
    { start: 0xFE00, end: 0xFE0F, name: "Variation Selectors", enabled: true, },
    { start: 0xFE20, end: 0xFE2F, name: "Combining Half Marks", enabled: true, },
    { start: 0xFE30, end: 0xFE4F, name: "CJK Compatibility Forms", enabled: true, },
    { start: 0xFE50, end: 0xFE6F, name: "Small Form Variants", enabled: true, },
    { start: 0xFE70, end: 0xFEFF, name: "Arabic Presentation Forms-B", enabled: true, },
    { start: 0xFF00, end: 0xFFEF, name: "Halfwidth and Fullwidth Forms", enabled: true, },
    { start: 0xFFF0, end: 0xFFFF, name: "Specials", enabled: true, },
    { start: 0x10000, end: 0x1007F, name: "Linear B Syllabary", enabled: true, },
    { start: 0x10080, end: 0x100FF, name: "Linear B Ideograms", enabled: true, },
    { start: 0x10100, end: 0x1013F, name: "Aegean Numbers", enabled: true, },
    { start: 0x10300, end: 0x1032F, name: "Old Italic", enabled: true, },
    { start: 0x10330, end: 0x1034F, name: "Gothic", enabled: true, },
    { start: 0x10380, end: 0x1039F, name: "Ugaritic", enabled: true, },
    { start: 0x10400, end: 0x1044F, name: "Deseret", enabled: true, },
    { start: 0x10450, end: 0x1047F, name: "Shavian", enabled: true, },
    { start: 0x10480, end: 0x104AF, name: "Osmanya", enabled: true, },
    { start: 0x10800, end: 0x1083F, name: "Cypriot Syllabary", enabled: true, },
    { start: 0x1D000, end: 0x1D0FF, name: "Byzantine Musical Symbols", enabled: true, },
    { start: 0x1D100, end: 0x1D1FF, name: "Musical Symbols", enabled: true, },
    { start: 0x1D300, end: 0x1D35F, name: "Tai Xuan Jing Symbols", enabled: true, },
    { start: 0x1D400, end: 0x1D7FF, name: "Mathematical Alphanumeric Symbols", enabled: true, },
    { start: 0x20000, end: 0x2A6DF, name: "CJK Unified Ideographs Extension B", enabled: true, },
    { start: 0x2F800, end: 0x2FA1F, name: "CJK Compatibility Ideographs Supplement", enabled: true, },
    { start: 0xE0000, end: 0xE007F, name: "Tags", enabled: true, },
].filter(v=>v.enabled);